# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Digidentity' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Digidentity
  pod 'Alamofire', '~> 4.5'
  pod 'AlamofireObjectMapper', '~> 5.0'
  pod 'ObjectMapper', '~> 3.1'
  pod 'SimpleImageViewer'
  pod 'TesseractOCRiOS'
  pod 'APESuperHUD', :git => 'https://github.com/apegroup/APESuperHUD.git'
  pod 'DataCache'
  pod 'SCLAlertView'

end
